language: elixir
matrix:
  include:
    - otp_release: 23.0.4
      elixir: 1.11.2
    - otp_release: 22.3
      elixir: 1.11.2
    - otp_release: 23.0.4
      elixir: 1.10.4
    - otp_release: 22.3
      elixir: 1.10.4
    - otp_release: 22.3
      elixir: 1.9.4
    - otp_release: 21.3
      elixir: 1.9.4
    - otp_release: 20.3
      elixir: 1.9.4
sudo: false
before_script:
  - mix deps.get --only test
script:
  - mix test
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
